<a href="https://colab.research.google.com/github/Meghana12c/Deep-Learning-Lab-Programs/blob/main/Deep_Learning_lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
# Scalar example
scalar = np.array(5)
print("Scalar value:", scalar)

Scalar value: 5


Lab 1


In [2]:
import numpy as np

# Scalar example
scalar = np.array(5)
print("Scalar value:", scalar)

# Vector example
vector = np.array([1, 2, 3])
print("Vector values:", vector)

# 2D Tensor (Matrix) example
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Tensor (Matrix):\n", matrix)

# 3D Tensor example
tensor_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D Tensor:\n", tensor_3d)

# 4D Tensor example
tensor_4d = np.random.rand(2, 3, 4, 5)
print("Shape of 4D Tensor:", tensor_4d.shape)


Scalar value: 5
Vector values: [1 2 3]
2D Tensor (Matrix):
 [[1 2 3]
 [4 5 6]]
3D Tensor:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape of 4D Tensor: (2, 3, 4, 5)


Program to predict sum of two numbers


In [3]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split

# Step 1: Generate Training Data
def generate_data(num_samples):
    x1 = np.random.randint(0, 100, size=num_samples)
    x2 = np.random.randint(0, 100, size=num_samples)
    y = x1 + x2
    return np.vstack((x1, x2)).T, y

num_samples = 10000
X, y = generate_data(num_samples)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 2: Define the Model
model = Sequential()
model.add(Dense(10, input_dim=2, activation='relu'))  # Input layer with 2 inputs
model.add(Dense(5, activation='relu'))  # Hidden layer
model.add(Dense(1))  # Output layer

# Step 3: Compile the Model
model.compile(optimizer='adam', loss='mean_squared_error')

# Step 4: Train the Model
model.fit(X_train, y_train, epochs=5, batch_size=64, validation_split=0.3)

# Step 5: Evaluate the Model
loss = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss}')

# Make a prediction
sample_input = np.array([[23, 45]])  # Example input
predicted_sum = model.predict(sample_input)
print(f'Predicted Sum: {predicted_sum[0][0]}')


Epoch 1/5
88/88 [==============================] - 1s 5ms/step - loss: 7046.8672 - val_loss: 2831.8740
Epoch 2/5
88/88 [==============================] - 0s 2ms/step - loss: 1157.4276 - val_loss: 345.1218
Epoch 3/5
88/88 [==============================] - 0s 3ms/step - loss: 211.8691 - val_loss: 113.0675
Epoch 4/5
88/88 [==============================] - 0s 3ms/step - loss: 79.2248 - val_loss: 47.4369
Epoch 5/5
63/63 [==============================] - 0s 1ms/step - loss: 27.3516
Test Loss: 27.35163116455078
1/1 [==============================] - 0s 88ms/step
Predicted Sum: 68.32715606689453


In [4]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split

# Step 1: Generate Training Data
def generate_data(num_samples):
    x1 = np.random.randint(0, 100, size=num_samples)
    x2 = np.random.randint(0, 100, size=num_samples)
    y = x1 + x2
    return np.vstack((x1, x2)).T, y

num_samples = 10000
X, y = generate_data(num_samples)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 2: Define the Model
model = Sequential()
model.add(Dense(10, input_dim=2, activation='relu'))  # Input layer with 2 inputs
model.add(Dense(5, activation='relu'))  # Hidden layer
model.add(Dense(1))  # Output layer

# Step 3: Compile the Model
model.compile(optimizer='adam', loss='mean_squared_error')

# Step 4: Train the Model
model.fit(X_train, y_train, epochs=8, batch_size=75, validation_split=0.5)

# Step 5: Evaluate the Model
loss = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss}')

# Make a prediction
sample_input = np.array([[23, 45]])  # Example input
predicted_sum = model.predict(sample_input)
print(f'Predicted Sum: {predicted_sum[0][0]}')


Epoch 1/8
54/54 [==============================] - 1s 8ms/step - loss: 9958.1074 - val_loss: 7906.5112
Epoch 2/8
54/54 [==============================] - 0s 4ms/step - loss: 5946.4751 - val_loss: 3603.1567
Epoch 3/8
54/54 [==============================] - 0s 5ms/step - loss: 1844.8521 - val_loss: 449.2757
Epoch 4/8
54/54 [==============================] - 0s 3ms/step - loss: 188.6926 - val_loss: 62.9943
Epoch 5/8
54/54 [==============================] - 0s 4ms/step - loss: 36.9931 - val_loss: 20.9941
Epoch 6/8
54/54 [==============================] - 0s 6ms/step - loss: 17.6318 - val_loss: 14.2978
Epoch 7/8
54/54 [==============================] - 0s 5ms/step - loss: 13.6018 - val_loss: 12.0459
Epoch 8/8
63/63 [==============================] - 0s 2ms/step - loss: 10.6157
Test Loss: 10.61569881439209
1/1 [==============================] - 0s 84ms/step
Predicted Sum: 66.21331024169922
