<a href="https://colab.research.google.com/github/Meghana12c/Deep-Learning-Lab-Programs/blob/main/DL_Lab_programs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Addition of Matrices


In [ ]:
def create_matrix(rows, cols):
    matrix = []
    print(f"Enter the elements of the {rows}x{cols} matrix:")
    for i in range(rows):
        row = list(map(int, input(f"Row {i + 1}: ").split()))
        if len(row) != cols:
            print(f"Please enter exactly {cols} numbers.")
            return create_matrix(rows, cols)
        matrix.append(row)
    return matrix

def add_matrices(matrix1, matrix2):
    return [[matrix1[i][j] + matrix2[i][j] for j in range(len(matrix1[0]))] for i in range(len(matrix1))]

def main():
    rows = int(input("Enter number of rows: "))
    cols = int(input("Enter number of columns: "))

    print("Matrix 1:")
    matrix1 = create_matrix(rows, cols)

    print("Matrix 2:")
    matrix2 = create_matrix(rows, cols)

    result_matrix = add_matrices(matrix1, matrix2)

    print("\nMatrix 1:")
    for row in matrix1:
        print(row)

    print("\nMatrix 2:")
    for row in matrix2:
        print(row)

    print("\nResultant Matrix after Addition:")
    for row in result_matrix:
        print(row)

if __name__ == "__main__":
    main()


Enter number of rows: 3
Enter number of columns: 3
Matrix 1:
Enter the elements of the 3x3 matrix:
Row 1: 1 2 3
Row 2: 5 6 7
Row 3: 3 7 9
Matrix 2:
Enter the elements of the 3x3 matrix:
Row 1: 1 4 3
Row 2: 5 6 9
Row 3: 3 4 9

Matrix 1:
[1, 2, 3]
[5, 6, 7]
[3, 7, 9]

Matrix 2:
[1, 4, 3]
[5, 6, 9]
[3, 4, 9]

Resultant Matrix after Addition:
[2, 6, 6]
[10, 12, 16]
[6, 11, 18]


Multiplication of Matrices


In [ ]:
import numpy as np

def create_random_matrix(n):
    return np.random.randint(1, 10, (n, n))

def matrix_multiplication(matrix_a, matrix_b):
    return np.dot(matrix_a, matrix_b)

def main():
    n = int(input("Enter the size of the matrices (n): "))


    matrix_a = create_random_matrix(n)
    matrix_b = create_random_matrix(n)

    print("Matrix A:")
    print(matrix_a)

    print("\nMatrix B:")
    print(matrix_b)


    result = matrix_multiplication(matrix_a, matrix_b)

    print("\nResult of A x B:")
    print(result)

if __name__ == "__main__":
    main()


Enter the size of the matrices (n): 2
Matrix A:
[[7 8]
 [8 7]]

Matrix B:
[[4 4]
 [5 1]]

Result of A x B:
[[68 36]
 [67 39]]


Subtraction of Matrices

In [ ]:
def matrix_subtraction():

    rows = int(input("Enter the number of rows: "))
    cols = int(input("Enter the number of columns: "))
    matrix1 = []
    matrix2 = []
    print("Enter elements of the first matrix:")
    for i in range(rows):
        row = []
        for j in range(cols):
            element = float(input(f"Enter element [{i+1}][{j+1}]: "))
            row.append(element)
        matrix1.append(row)
    print("Enter elements of the second matrix:")
    for i in range(rows):
        row = []
        for j in range(cols):
            element = float(input(f"Enter element [{i+1}][{j+1}]: "))
            row.append(element)
        matrix2.append(row)
    result_matrix = []
    for i in range(rows):
        row = []
        for j in range(cols):
            element = matrix1[i][j] - matrix2[i][j]
            row.append(element)
        result_matrix.append(row)
    print("\nResultant matrix (Matrix1 - Matrix2):")
    for row in result_matrix:
        print(row)
matrix_subtraction()

Enter the number of rows: 3
Enter the number of columns: 3
Enter elements of the first matrix:
Enter element [1][1]: 3
Enter element [1][2]: 4
Enter element [1][3]: 2
Enter element [2][1]: 5
Enter element [2][2]: 2
Enter element [2][3]: 7
Enter element [3][1]: 9
Enter element [3][2]: 1
Enter element [3][3]: 0
Enter elements of the second matrix:
Enter element [1][1]: 4
Enter element [1][2]: 6
Enter element [1][3]: 2
Enter element [2][1]: 8
Enter element [2][2]: 0
Enter element [2][3]: 7
Enter element [3][1]: 3
Enter element [3][2]: 2
Enter element [3][3]: 1

Resultant matrix (Matrix1 - Matrix2):
[-1.0, -2.0, 0.0]
[-3.0, 2.0, 0.0]
[6.0, -1.0, -1.0]


Division of Matrices

In [ ]:
def matrix_division():1
    rows = int(input("Enter the number of rows: "))
    cols = int(input("Enter the number of columns: "))
    matrix1 = []
    matrix2 = []
    print("Enter elements of the first matrix:")
    for i in range(rows):
        row = []
        for j in range(cols):
            element = float(input(f"Enter element [{i+1}][{j+1}]: "))
            row.append(element)
        matrix1.append(row)
    print("Enter elements of the second matrix:")
    for i in range(rows):
        row = []
        for j in range(cols):
            element = float(input(f"Enter element [{i+1}][{j+1}]: "))
            row.append(element)
        matrix2.append(row)
    result_matrix = []
    for i in range(rows):
        row = []
        for j in range(cols):
            if matrix2[i][j] != 0:
                element = matrix1[i][j] / matrix2[i][j]
            else:
                print("Error: Division by zero encountered.")
                return
            row.append(element)
        result_matrix.append(row)
    print("\nResultant matrix (Matrix1 / Matrix2):")
    for row in result_matrix:
        print(row)
matrix_division()

Enter the number of rows: 2
Enter the number of columns: 2
Enter elements of the first matrix:
Enter element [1][1]: 2
Enter element [1][2]: 4
Enter element [2][1]: 6
Enter element [2][2]: 2
Enter elements of the second matrix:
Enter element [1][1]: 5
Enter element [1][2]: 6
Enter element [2][1]: 3
Enter element [2][2]: 1

Resultant matrix (Matrix1 / Matrix2):
[0.4, 0.6666666666666666]
[2.0, 2.0]


Transpose of Matrices

In [ ]:
import numpy as np
def transpose_matrix(matrix):
    return np.transpose(matrix)
n = int(input("Enter the size of the matrix (n x n): "))
matrix = []

print("Enter the elements of the matrix row by row:")
for i in range(n):
    row = list(map(float, input(f"Row {i+1}: ").split()))
    matrix.append(row)
matrix = np.array(matrix)
transposed = transpose_matrix(matrix)
print("Transposed matrix:")
print(transposed)


Enter the size of the matrix (n x n): 3
Enter the elements of the matrix row by row:
Row 1: 2
Row 2: 4
Row 3: 7
Transposed matrix:
[[2. 4. 7.]]


Week 2 lab


Matrix multiplication using keras


In [5]:
!pip install tensorflow


In [6]:
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Dot
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
input1 = Input(shape=(2,))
input2 = Input(shape=(2,))
output = Dot(axes=1)([input1, input2])
model = Model(inputs=[input1, input2], outputs=output)
model.compile(optimizer='adam', loss='mean_squared_error')
result = model.predict([matrix1, matrix2])
print("Result of matrix multiplication:")
print(result)
!pip install tensorflow
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dot
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
input1 = Input(shape=(2,))
input2 = Input(shape=(2,))
output = Dot(axes=1)([input1, input2])
model = Model(inputs=[input1, input2], outputs=output)
model.compile(optimizer='adam', loss='mean_squared_error')
result = model.predict([matrix1, matrix2])
print("Result of matrix multiplication:")
print(result)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step
Result of matrix multiplication:
[[17.]
 [53.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
Result of matrix multiplication:
[[17.]
 [53.]]


Prime numbers using keras


In [9]:
!pip install tensorflow
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
def is_prime(n):
    if n <= 1:
        return 0
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return 0
    return 1

# Generate data
X = np.arange(1, 101)
y = np.array([is_prime(x) for x in X])
model = Sequential([
    Dense(64, activation='relu', input_shape=(1,)),
    Dense(64, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X, y, epochs=100, batch_size=10)
# Function to check if a number is prime using the trained model
def check_prime(number):
    prediction = model.predict(np.array([number]))
    return prediction[0][0] > 0.5

# Get user input
user_input = int(input("Enter a number to check if it's prime: "))
if check_prime(user_input):
    print(f"{user_input} is a prime number.")
else:
    print(f"{user_input} is not a prime number.")
    # Install TensorFlow
!pip install tensorflow

# Import necessary libraries
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return 0
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return 0
    return 1

# Generate data
X = np.arange(1, 101)
y = np.array([is_prime(x) for x in X])

# Create the Keras model
model = Sequential([
    Dense(64, activation='relu', input_shape=(1,)),
    Dense(64, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X, y, epochs=100, batch_size=10)

# Function to check if a number is prime using the trained model
def check_prime(number):
    prediction = model.predict(np.array([number]))
    return prediction[0][0] > 0.5

# Get user input
user_input = int(input("Enter a number to check if it's prime: "))
if check_prime(user_input):
    print(f"{user_input} is a prime number.")
else:
    print(f"{user_input} is not a prime number.")








Epoch 1/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.3487 - loss: 2.4853
Epoch 2/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7741 - loss: 1.1300 
Epoch 3/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7203 - loss: 0.7900 
Epoch 4/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7978 - loss: 0.5858 
Epoch 5/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7034 - loss: 0.6225 
Epoch 6/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7166 - loss: 0.6117 
Epoch 7/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7660 - loss: 0.5722 
Epoch 8/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7417 - loss: 0.5591 
Epoch 9/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7041 - loss: 0.5888 
Epoch 10/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7900 - loss: 0.5357 
Epoch 11/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7376 - loss: 0.6348  
Epoch 12/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step
3 is not a prime number.
Epoch 1/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5289 - loss: 1.8497
Epoch 2/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7317 - loss: 0.9150 
Epoch 3/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5495 - loss: 0.6894 
Epoch 4/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7547 - loss: 0.7192 
Epoch 5/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7826 - loss: 0.6005 
Epoch 6/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8112 - loss: 0.5544 
Epoch 7/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7442 - loss: 0.5481 
Epoch 8/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7147 - loss: 0.5828  
Epoch 9/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7952 - loss: 0.5222 
Epoch 10/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7511 - loss: 0.5560 
Epoch 11/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7705 - los