<a href="https://colab.research.google.com/github/Meghana12c/Deep-Learning-Lab-Programs/blob/main/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Addition of Matrices


In [6]:
def create_matrix(rows, cols):
    matrix = []
    print(f"Enter the elements of the {rows}x{cols} matrix:")
    for i in range(rows):
        row = list(map(int, input(f"Row {i + 1}: ").split()))
        if len(row) != cols:
            print(f"Please enter exactly {cols} numbers.")
            return create_matrix(rows, cols)
        matrix.append(row)
    return matrix

def add_matrices(matrix1, matrix2):
    return [[matrix1[i][j] + matrix2[i][j] for j in range(len(matrix1[0]))] for i in range(len(matrix1))]

def main():
    rows = int(input("Enter number of rows: "))
    cols = int(input("Enter number of columns: "))

    print("Matrix 1:")
    matrix1 = create_matrix(rows, cols)

    print("Matrix 2:")
    matrix2 = create_matrix(rows, cols)

    result_matrix = add_matrices(matrix1, matrix2)

    print("\nMatrix 1:")
    for row in matrix1:
        print(row)

    print("\nMatrix 2:")
    for row in matrix2:
        print(row)

    print("\nResultant Matrix after Addition:")
    for row in result_matrix:
        print(row)

if __name__ == "__main__":
    main()


Enter number of rows: 3
Enter number of columns: 3
Matrix 1:
Enter the elements of the 3x3 matrix:
Row 1: 1 2 3
Row 2: 5 6 7
Row 3: 3 7 9
Matrix 2:
Enter the elements of the 3x3 matrix:
Row 1: 1 4 3
Row 2: 5 6 9
Row 3: 3 4 9

Matrix 1:
[1, 2, 3]
[5, 6, 7]
[3, 7, 9]

Matrix 2:
[1, 4, 3]
[5, 6, 9]
[3, 4, 9]

Resultant Matrix after Addition:
[2, 6, 6]
[10, 12, 16]
[6, 11, 18]


Multiplication of Matrices


In [7]:
import numpy as np

def create_random_matrix(n):
    return np.random.randint(1, 10, (n, n))

def matrix_multiplication(matrix_a, matrix_b):
    return np.dot(matrix_a, matrix_b)

def main():
    n = int(input("Enter the size of the matrices (n): "))


    matrix_a = create_random_matrix(n)
    matrix_b = create_random_matrix(n)

    print("Matrix A:")
    print(matrix_a)

    print("\nMatrix B:")
    print(matrix_b)


    result = matrix_multiplication(matrix_a, matrix_b)

    print("\nResult of A x B:")
    print(result)

if __name__ == "__main__":
    main()


Enter the size of the matrices (n): 2
Matrix A:
[[7 8]
 [8 7]]

Matrix B:
[[4 4]
 [5 1]]

Result of A x B:
[[68 36]
 [67 39]]


Subtraction of Matrices

In [8]:
def matrix_subtraction():

    rows = int(input("Enter the number of rows: "))
    cols = int(input("Enter the number of columns: "))
    matrix1 = []
    matrix2 = []
    print("Enter elements of the first matrix:")
    for i in range(rows):
        row = []
        for j in range(cols):
            element = float(input(f"Enter element [{i+1}][{j+1}]: "))
            row.append(element)
        matrix1.append(row)
    print("Enter elements of the second matrix:")
    for i in range(rows):
        row = []
        for j in range(cols):
            element = float(input(f"Enter element [{i+1}][{j+1}]: "))
            row.append(element)
        matrix2.append(row)
    result_matrix = []
    for i in range(rows):
        row = []
        for j in range(cols):
            element = matrix1[i][j] - matrix2[i][j]
            row.append(element)
        result_matrix.append(row)
    print("\nResultant matrix (Matrix1 - Matrix2):")
    for row in result_matrix:
        print(row)
matrix_subtraction()

Enter the number of rows: 3
Enter the number of columns: 3
Enter elements of the first matrix:
Enter element [1][1]: 3
Enter element [1][2]: 4
Enter element [1][3]: 2
Enter element [2][1]: 5
Enter element [2][2]: 2
Enter element [2][3]: 7
Enter element [3][1]: 9
Enter element [3][2]: 1
Enter element [3][3]: 0
Enter elements of the second matrix:
Enter element [1][1]: 4
Enter element [1][2]: 6
Enter element [1][3]: 2
Enter element [2][1]: 8
Enter element [2][2]: 0
Enter element [2][3]: 7
Enter element [3][1]: 3
Enter element [3][2]: 2
Enter element [3][3]: 1

Resultant matrix (Matrix1 - Matrix2):
[-1.0, -2.0, 0.0]
[-3.0, 2.0, 0.0]
[6.0, -1.0, -1.0]


Division of Matrices

In [10]:
def matrix_division():1
    rows = int(input("Enter the number of rows: "))
    cols = int(input("Enter the number of columns: "))
    matrix1 = []
    matrix2 = []
    print("Enter elements of the first matrix:")
    for i in range(rows):
        row = []
        for j in range(cols):
            element = float(input(f"Enter element [{i+1}][{j+1}]: "))
            row.append(element)
        matrix1.append(row)
    print("Enter elements of the second matrix:")
    for i in range(rows):
        row = []
        for j in range(cols):
            element = float(input(f"Enter element [{i+1}][{j+1}]: "))
            row.append(element)
        matrix2.append(row)
    result_matrix = []
    for i in range(rows):
        row = []
        for j in range(cols):
            if matrix2[i][j] != 0:
                element = matrix1[i][j] / matrix2[i][j]
            else:
                print("Error: Division by zero encountered.")
                return
            row.append(element)
        result_matrix.append(row)
    print("\nResultant matrix (Matrix1 / Matrix2):")
    for row in result_matrix:
        print(row)
matrix_division()

Enter the number of rows: 2
Enter the number of columns: 2
Enter elements of the first matrix:
Enter element [1][1]: 2
Enter element [1][2]: 4
Enter element [2][1]: 6
Enter element [2][2]: 2
Enter elements of the second matrix:
Enter element [1][1]: 5
Enter element [1][2]: 6
Enter element [2][1]: 3
Enter element [2][2]: 1

Resultant matrix (Matrix1 / Matrix2):
[0.4, 0.6666666666666666]
[2.0, 2.0]


Transpose of Matrices

In [12]:
import numpy as np
def transpose_matrix(matrix):
    return np.transpose(matrix)
n = int(input("Enter the size of the matrix (n x n): "))
matrix = []

print("Enter the elements of the matrix row by row:")
for i in range(n):
    row = list(map(float, input(f"Row {i+1}: ").split()))
    matrix.append(row)
matrix = np.array(matrix)
transposed = transpose_matrix(matrix)
print("Transposed matrix:")
print(transposed)


Enter the size of the matrix (n x n): 3
Enter the elements of the matrix row by row:
Row 1: 2
Row 2: 4
Row 3: 7
Transposed matrix:
[[2. 4. 7.]]
