<a href="https://colab.research.google.com/github/Meghana12c/Deep-Learning-Programs/blob/main/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Addition of Matrices


In [6]:
def create_matrix(rows, cols):
    matrix = []
    print(f"Enter the elements of the {rows}x{cols} matrix:")
    for i in range(rows):
        row = list(map(int, input(f"Row {i + 1}: ").split()))
        if len(row) != cols:
            print(f"Please enter exactly {cols} numbers.")
            return create_matrix(rows, cols)
        matrix.append(row)
    return matrix

def add_matrices(matrix1, matrix2):
    return [[matrix1[i][j] + matrix2[i][j] for j in range(len(matrix1[0]))] for i in range(len(matrix1))]

def main():
    rows = int(input("Enter number of rows: "))
    cols = int(input("Enter number of columns: "))

    print("Matrix 1:")
    matrix1 = create_matrix(rows, cols)

    print("Matrix 2:")
    matrix2 = create_matrix(rows, cols)

    result_matrix = add_matrices(matrix1, matrix2)

    print("\nMatrix 1:")
    for row in matrix1:
        print(row)

    print("\nMatrix 2:")
    for row in matrix2:
        print(row)

    print("\nResultant Matrix after Addition:")
    for row in result_matrix:
        print(row)

if __name__ == "__main__":
    main()


Enter number of rows: 3
Enter number of columns: 3
Matrix 1:
Enter the elements of the 3x3 matrix:
Row 1: 1 2 3
Row 2: 5 6 7
Row 3: 3 7 9
Matrix 2:
Enter the elements of the 3x3 matrix:
Row 1: 1 4 3
Row 2: 5 6 9
Row 3: 3 4 9

Matrix 1:
[1, 2, 3]
[5, 6, 7]
[3, 7, 9]

Matrix 2:
[1, 4, 3]
[5, 6, 9]
[3, 4, 9]

Resultant Matrix after Addition:
[2, 6, 6]
[10, 12, 16]
[6, 11, 18]


Multiplication of Matrices


In [7]:
import numpy as np

def create_random_matrix(n):
    return np.random.randint(1, 10, (n, n))

def matrix_multiplication(matrix_a, matrix_b):
    return np.dot(matrix_a, matrix_b)

def main():
    n = int(input("Enter the size of the matrices (n): "))


    matrix_a = create_random_matrix(n)
    matrix_b = create_random_matrix(n)

    print("Matrix A:")
    print(matrix_a)

    print("\nMatrix B:")
    print(matrix_b)


    result = matrix_multiplication(matrix_a, matrix_b)

    print("\nResult of A x B:")
    print(result)

if __name__ == "__main__":
    main()


Enter the size of the matrices (n): 2
Matrix A:
[[7 8]
 [8 7]]

Matrix B:
[[4 4]
 [5 1]]

Result of A x B:
[[68 36]
 [67 39]]
